### ISSUE TITLE
germinae returns nothing

### ISSUE THREAD

**Issue by cqb13** [sjgallagher2/PyWORDS#4]
should return something like this, i think
{'text': 'germen', 'forms': [{'text': 'germen', 'analyses': {21498: {'lexeme': {'id': 21498, 'category': [3, 2], 'roots': ['germen', 'germin'], 'senses': ['sprout, bud', 'shoot'], 'wordType': <WordType.N: 'Noun'>, 'form': ['N', 'T'], 'props': ['X', 'A', 'X', 'B', 'X'], 'parsed_props': {'Age': 'DEFAULT', 'Area': 'Agriculture', 'Geography': 'Default', 'Frequency': 'Frequent', 'Source': 'General or unknown or too common to say'}}, 'root': '', 'inflections': [{'wordType': <WordType.N: 'Noun'>, 'category': [3, 0], 'stem': 'germen', 'affix': '', 'features': {'Case': <Case.NOM: 'Nominative'>, 'Number': <Number.S: 'Singular'>, 'Gender': <Gender.N: 'Neuter'>}, 'id': 279}, {'wordType': <WordType.N: 'Noun'>, 'category': [3, 0], 'stem': 'germen', 'affix': '', 'features': {'Case': <Case.VOC: 'Vocative'>, 'Number': <Number.S: 'Singular'>, 'Gender': <Gender.N: 'Neuter'>}, 'id': 280}, {'wordType': <WordType.N: 'Noun'>, 'category': [3, 2], 'stem': 'germen', 'affix': '', 'features': {'Case': <Case.ACC: 'Accusative'>, 'Number': <Number.S: 'Singular'>, 'Gender': <Gender.N: 'Neuter'>}, 'id': 308}], 'enclitic': None}}, 'enclitic': None}]}

**Comment by sjgallagher2** [comment]
_germinae_ seems to be an incorrect declination, it's a neuter 3rd decl (var 2), so nothing should be returned in this case
